### ISSUE TITLE
Does not work with tModLoader 1.4 alpha

### ISSUE THREAD

**Issue by UnusedCactus** [DRKV333/ShopExpander#4]
Whenever I try to use this mod with the tModLoader 1.4 alpha version it spits out this error:
> [16:14:52] [.NET ThreadPool Worker/ERROR] [tML]: An error occurred while loading ShopExpander
> It has been detected that this mod was built for tModLoader v0.10.1.5
> However, you are using tModLoader v2022.3.35.12
> The mod(s) have been automatically disabled.
> System.ArgumentNullException: Buffer cannot be null. (Parameter 'buffer')
>    at System.IO.MemoryStream..ctor(Byte[] buffer, Boolean writable)
>    at Terraria.ModLoader.Core.AssemblyManager.ModLoadContext.LoadAssembly(Byte[] code, Byte[] pdb) in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 68
>    at Terraria.ModLoader.Core.AssemblyManager.ModLoadContext.LoadAssemblies() in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 56
>    at Terraria.ModLoader.Core.AssemblyManager.InstantiateMods(List`1 modsToLoad, CancellationToken token) in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 208
>    at Terraria.ModLoader.Core.ModOrganizer.LoadMods(CancellationToken token) in tModLoader\Terraria\ModLoader\Core\ModOrganizer.cs:line 143
>    at Terraria.ModLoader.ModLoader.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModLoader.cs:line 117
> [16:14:52] [.NET ThreadPool Worker/INFO] [tML]: Disabling Mod: ShopExpander
> [16:14:56] [Main Thread/DEBUG] [tML]: Process.Start (UseShellExecute = True): "tModLoader-Logs"

**Comment by DRKV333** [comment]
Well, that's not entirely unexpected, considering your tML is a whole _2022_ major versions ahead.
Jokes aside, there might be 1.4 port some time in the future, either by me, or a new maintainer.
